%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-moveit-commander
Version:        1.1.6
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS moveit_commander package

License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-assimp
Requires:       python3-devel
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-moveit-msgs
Requires:       ros-noetic-moveit-ros-planning-interface
Requires:       ros-noetic-rospy
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-shape-msgs
Requires:       ros-noetic-tf
BuildRequires:  python3-catkin_pkg
BuildRequires:  python3-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-moveit-resources-fanuc-moveit-config
BuildRequires:  ros-noetic-rostest
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Python interfaces to MoveIt

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Sat Nov 06 2021 Michael Görner <me@v4hn.de> - 1.1.6-1
- Autogenerated by Bloom

* Sun May 23 2021 Michael Görner <me@v4hn.de> - 1.1.5-1
- Autogenerated by Bloom

* Sun May 23 2021 Michael Görner <me@v4hn.de> - 1.1.4-2
- Autogenerated by Bloom

* Wed May 12 2021 Michael Görner <me@v4hn.de> - 1.1.4-1
- Autogenerated by Bloom

* Tue May 04 2021 Michael Görner <me@v4hn.de> - 1.1.3-1
- Autogenerated by Bloom

* Fri Apr 09 2021 Michael Görner <me@v4hn.de> - 1.1.2-1
- Autogenerated by Bloom

* Tue Oct 13 2020 Michael Görner <me@v4hn.de> - 1.1.1-1
- Autogenerated by Bloom

* Mon Sep 07 2020 Michael Görner <me@v4hn.de> - 1.1.0-1
- Autogenerated by Bloom

