Name:           ros-lunar-moveit-ros-perception
Version:        0.9.10
Release:        0%{?dist}
Summary:        ROS moveit_ros_perception package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       freeglut-devel
Requires:       glew-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       ros-lunar-cv-bridge
Requires:       ros-lunar-image-transport
Requires:       ros-lunar-message-filters
Requires:       ros-lunar-moveit-core
Requires:       ros-lunar-moveit-msgs
Requires:       ros-lunar-octomap
Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-rosconsole
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-tf
Requires:       ros-lunar-tf-conversions
Requires:       ros-lunar-urdf
BuildRequires:  eigen3-devel
BuildRequires:  freeglut-devel
BuildRequires:  glew-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-cv-bridge
BuildRequires:  ros-lunar-image-transport
BuildRequires:  ros-lunar-message-filters
BuildRequires:  ros-lunar-moveit-core
BuildRequires:  ros-lunar-moveit-msgs
BuildRequires:  ros-lunar-octomap
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-rosconsole
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-tf
BuildRequires:  ros-lunar-tf-conversions
BuildRequires:  ros-lunar-urdf

%description
Components of MoveIt connecting to perception

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Sat Dec 09 2017 Michael Ferguson <mferguson@fetchrobotics.com> - 0.9.10-0
- Autogenerated by Bloom

* Sun Aug 06 2017 Ioan Sucan <isucan@google.com> - 0.9.9-0
- Autogenerated by Bloom

* Wed Jun 21 2017 Ioan Sucan <isucan@google.com> - 0.9.8-0
- Autogenerated by Bloom

* Mon Jun 05 2017 Ioan Sucan <isucan@google.com> - 0.9.7-0
- Autogenerated by Bloom

* Fri May 12 2017 Ioan Sucan <isucan@google.com> - 0.9.6-1
- Autogenerated by Bloom

* Wed May 10 2017 Ioan Sucan <isucan@google.com> - 0.9.6-0
- Autogenerated by Bloom

