Name:           ros-kinetic-moveit-ros-control-interface
Version:        0.9.5
Release:        1%{?dist}
Summary:        ROS moveit_ros_control_interface package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-controller-manager-msgs
Requires:       ros-kinetic-moveit-core
Requires:       ros-kinetic-moveit-simple-controller-manager
Requires:       ros-kinetic-pluginlib >= 1.10.4
Requires:       ros-kinetic-trajectory-msgs
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-controller-manager-msgs
BuildRequires:  ros-kinetic-moveit-core
BuildRequires:  ros-kinetic-moveit-simple-controller-manager
BuildRequires:  ros-kinetic-pluginlib >= 1.10.4
BuildRequires:  ros-kinetic-trajectory-msgs

%description
ros_control controller manager interface for MoveIt!

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Apr 08 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.9.5-1
- Autogenerated by Bloom

* Wed Mar 08 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.9.5-0
- Autogenerated by Bloom

* Mon Feb 06 2017 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.9.4-0
- Autogenerated by Bloom

* Wed Nov 16 2016 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.9.3-0
- Autogenerated by Bloom

* Sun Nov 13 2016 Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de> - 0.9.2-1
- Autogenerated by Bloom

