Name:           ros-melodic-moveit-core
Version:        1.0.2
Release:        1%{?dist}
Summary:        ROS moveit_core package

Group:          Development/Libraries
License:        BSD
URL:            http://moveit.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       console-bridge-devel
Requires:       eigen3-devel
Requires:       fcl-devel
Requires:       ros-melodic-eigen-stl-containers
Requires:       ros-melodic-geometric-shapes >= 0.5.2
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-kdl-parser
Requires:       ros-melodic-moveit-msgs
Requires:       ros-melodic-octomap
Requires:       ros-melodic-octomap-msgs
Requires:       ros-melodic-random-numbers
Requires:       ros-melodic-rosconsole
Requires:       ros-melodic-roslib
Requires:       ros-melodic-rostime
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-shape-msgs
Requires:       ros-melodic-srdfdom
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf2-eigen
Requires:       ros-melodic-tf2-geometry-msgs
Requires:       ros-melodic-trajectory-msgs
Requires:       ros-melodic-urdf
Requires:       ros-melodic-visualization-msgs
Requires:       ros-melodic-xmlrpcpp
Requires:       urdfdom-devel
Requires:       urdfdom-headers-devel
BuildRequires:  assimp
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  console-bridge-devel
BuildRequires:  eigen3-devel
BuildRequires:  fcl-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-melodic-angles
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-code-coverage
BuildRequires:  ros-melodic-eigen-stl-containers
BuildRequires:  ros-melodic-geometric-shapes >= 0.5.2
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-kdl-parser
BuildRequires:  ros-melodic-moveit-msgs
BuildRequires:  ros-melodic-moveit-resources
BuildRequires:  ros-melodic-octomap
BuildRequires:  ros-melodic-octomap-msgs
BuildRequires:  ros-melodic-orocos-kdl
BuildRequires:  ros-melodic-random-numbers
BuildRequires:  ros-melodic-rosconsole
BuildRequires:  ros-melodic-roslib
BuildRequires:  ros-melodic-rostime
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-shape-msgs
BuildRequires:  ros-melodic-srdfdom
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf2-eigen
BuildRequires:  ros-melodic-tf2-geometry-msgs
BuildRequires:  ros-melodic-tf2-kdl
BuildRequires:  ros-melodic-trajectory-msgs
BuildRequires:  ros-melodic-urdf
BuildRequires:  ros-melodic-visualization-msgs
BuildRequires:  ros-melodic-xmlrpcpp
BuildRequires:  urdfdom-devel
BuildRequires:  urdfdom-headers-devel

%description
Core libraries used by MoveIt!

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jun 28 2019 Dave Coleman <dave@picknik.ai> - 1.0.2-1
- Autogenerated by Bloom

* Fri Mar 08 2019 Dave Coleman <dave@picknik.ai> - 1.0.1-0
- Autogenerated by Bloom

* Fri Mar 08 2019 Dave Coleman <dave@picknik.ai> - 1.0.0-1
- Autogenerated by Bloom

* Sun Feb 24 2019 Dave Coleman <dave@picknik.ai> - 1.0.0-0
- Autogenerated by Bloom

* Mon Dec 24 2018 Dave Coleman <dave@dav.ee> - 0.10.8-0
- Autogenerated by Bloom

* Thu Dec 13 2018 Dave Coleman <dave@dav.ee> - 0.10.7-0
- Autogenerated by Bloom

* Tue Dec 11 2018 Dave Coleman <dave@dav.ee> - 0.10.6-2
- Autogenerated by Bloom

* Mon Dec 10 2018 Dave Coleman <dave@dav.ee> - 0.10.6-1
- Autogenerated by Bloom

* Mon Dec 10 2018 Dave Coleman <dave@dav.ee> - 0.10.6-0
- Autogenerated by Bloom

* Thu Nov 01 2018 Dave Coleman <dave@dav.ee> - 0.10.5-0
- Autogenerated by Bloom

* Mon Oct 29 2018 Dave Coleman <dave@dav.ee> - 0.10.4-0
- Autogenerated by Bloom

* Mon Oct 29 2018 Dave Coleman <dave@dav.ee> - 0.10.3-0
- Autogenerated by Bloom

* Wed Oct 24 2018 Dave Coleman <dave@dav.ee> - 0.10.2-0
- Autogenerated by Bloom

* Fri May 25 2018 Dave Coleman <dave@dav.ee> - 0.10.1-0
- Autogenerated by Bloom

* Tue May 22 2018 Dave Coleman <dave@dav.ee> - 0.10.0-0
- Autogenerated by Bloom

